name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          set +e
          pwd
          ls -la
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      -  name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download and install Trivy
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo bash
          sudo mv ./bin/trivy /usr/local/bin/trivy  
          trivy --version  

      - name: Build Docker image
        run: docker build -f application/dockerfile -t my-app .

      - name: List Docker images
        run: |
          docker images  

      - name: Scan Docker Image with Trivy
        run: |
          trivy image --severity CRITICAL,HIGH my-app


      - name: Push Docker image
        run: | 
          docker tag my-app "${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest"
          
      - name: Push Docker image
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest"
 
