name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          set +e
          pwd
          ls -la
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      -  name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download and install Trivy
        run: |
          curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.30.0/trivy_0.30.0_Linux-x86_64.tar.gz -o trivy.tar.gz
          tar xzvf trivy.tar.gz
          sudo mv trivy /usr/local/bin/    

      - name: Build Docker image
        run: docker build -f application/dockerfile -t my-app .

      - name: Scan Docker Image with Trivy
        run: |
              trivy image ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      - name: Push Docker image
        run: | 
              docker tag my-app ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
              docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
 
 